# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a7dc200cb65d5b1ff9cd33407e60a49c5ccaf20eca494ca88fb448503e99b478750f9c2630d4b96367295b0aea7a4fec9f5ca3c8fc86c4ed1405beb46005ac2

test:
  secret_key_base: 91c584ebfd9afe4014c20e85c2ba8ccb27b44c24cc1a8ac397fe02585debb90310d085cd893775afc48481d16fb1565cffd685e0fcf5f9d38332b33ad27fa488

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
